```yaml
openapi: 3.0.0
info:
  title: Ice Sculpture Inventory API
  version: 1.0.0
  description: API for managing ice sculpture inventory.
paths:
  /sculptures:
    get:
      summary: Retrieve a list of ice sculptures
      operationId: listSculptures
      responses:
        '200':
          description: A list of ice sculptures.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Sculpture'
        '500':
          description: Internal server error.
    post:
      summary: Create a new ice sculpture
      operationId: createSculpture
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SculptureInput'
      responses:
        '200':
          description: The newly created ice sculpture.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Sculpture'
        '400':
          description: Bad request.
        '500':
          description: Internal server error.
  /sculptures/{sculptureId}:
    get:
      summary: Retrieve a specific ice sculpture by ID
      operationId: getSculptureById
      parameters:
        - name: sculptureId
          in: path
          required: true
          description: The ID of the sculpture to retrieve
          schema:
            type: string
      responses:
        '200':
          description: The requested ice sculpture.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Sculpture'
        '404':
          description: Sculpture not found.
        '500':
          description: Internal server error.
    put:
      summary: Update an existing ice sculpture
      operationId: updateSculpture
      parameters:
        - name: sculptureId
          in: path
          required: true
          description: The ID of the sculpture to update
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SculptureInput'
      responses:
        '200':
          description: The updated ice sculpture.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Sculpture'
        '400':
          description: Bad request.
        '404':
          description: Sculpture not found.
        '500':
          description: Internal server error.
    delete:
      summary: Delete an ice sculpture
      operationId: deleteSculpture
      parameters:
        - name: sculptureId
          in: path
          required: true
          description: The ID of the sculpture to delete
          schema:
            type: string
      responses:
        '200':
          description: Sculpture deleted successfully.
        '404':
          description: Sculpture not found.
        '500':
          description: Internal server error.
components:
  schemas:
    Sculpture:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier for the sculpture
          example: "a1b2c3d4e5"
        name:
          type: string
          description: Name of the ice sculpture
          example: "Winter Swan"
        artist:
          type: string
          description: Name of the artist who created the sculpture
          example: "Jane Doe"
        hoursToMelt:
          type: integer
          description: Number of hours until the sculpture completely melts
          example: 24
      required:
        - id
        - name
        - artist
        - hoursToMelt
    SculptureInput:
      type: object
      properties:
        name:
          type: string
          description: Name of the ice sculpture
          example: "Winter Swan"
        artist:
          type: string
          description: Name of the artist who created the sculpture
          example: "Jane Doe"
        hoursToMelt:
          type: integer
          description: Number of hours until the sculpture completely melts
          example: 24
      required:
        - name
        - artist
        - hoursToMelt
```

